CREATE TABLE PUBLIC.DATA_SOURCE_FACTORY
(
  ID           VARCHAR2(32) PRIMARY KEY NOT NULL,
  DRIVER       VARCHAR2(255)            NOT NULL,
  URLSTR       VARCHAR2(255)            NOT NULL,
  USERNAME     VARCHAR2(255)            NOT NULL,
  USERPASSWORD VARCHAR2(255)            NOT NULL
);


CREATE TABLE PUBLIC.DATA_TABLE
(
  ID                     VARCHAR2(32) PRIMARY KEY NOT NULL,
  DATA_SOURCE_FACTORY_ID VARCHAR2(32)             NOT NULL,
  TABLE_NAME             VARCHAR2(255)            NOT NULL,
  TABLE_REMARK           VARCHAR2(255)
);

CREATE TABLE PUBLIC.DATA_COLUMN
(
  ID            VARCHAR2(32) PRIMARY KEY NOT NULL,
  DATA_TABLE_ID VARCHAR2(32)             NOT NULL,
  COL_NAME      VARCHAR2(255)            NOT NULL,
  COL_LENGTH    VARCHAR2(10)             NOT NULL,
  COL_REMARK    VARCHAR2(255)
);


